### ISSUE TITLE
Transfer to dgutov?

### ISSUE THREAD

**Issue by purcell** [dgutov/mmm-mode#130]
Hey @dgutov, I rarely contribute usefully here these days — if you'd like the public credit for your ongoing work, I'd be happy to transfer this repo to you, just let me know.

**Comment by dgutov** [comment]
Since it's not the first time you're offering -- why not? Thanks for the confidence. :+1:

**Comment by purcell** [comment]
Request sent. Once done, I'll update the MELPA recipe, but due to Github's smart redirects, nothing should really break. Perhaps keep me as a collaborator in the repo in case I can help sometime. I think sometimes about adding CI, for example.

**Comment by dgutov** [comment]
> Perhaps keep me as a collaborator in the repo in case I can help sometime.

Of course.

Thank you.

**Comment by purcell** [comment]
Cool, I updated the MELPA recipe.
