### ISSUE TITLE
GNU ELPA does not build the mmm-mode.info file

### ISSUE THREAD

**Issue by snogge** [dgutov/mmm-mode#131]
The mmm-mode entry in `elpa/elpa-packages` does not have a :doc` entry, which I suspect is the reason no info file is generated and included in the package. @dgutov , do you have commit rights to elpa and can fix this?

**Comment by dgutov** [comment]
I do.

Should `:doc "mmm.texi"` be enough?

Do we still need `textinfo.tex` in the repository, BTW? From what I can see, other packages don't store it in the repo. Relying on the system installation, perhaps.

**Comment by snogge** [comment]
Please hold off with this, the current mmm.texi still has some problems.  I cannot build it locally with the elpa scripts, so I will have to investigate further. 
I'll also check the texinfo.tex file.

**Comment by snogge** [comment]
Found the problem with the mmm.texi file, a fix is in #132.
The texinfo.tex file is required by automake.  makeinfo itself finds the system installed file.

**Comment by dgutov** [comment]
Do we need to automake stuff still?

I've pushed the change to the elpa repo.

**Comment by snogge** [comment]
Are you sure? I can't see any update.

**Comment by dgutov** [comment]
My bad, forgot to push. Done now.
